baseurl = "https://ssyo.netlify.app"
title = "johndoe"

theme = "hugo-coder"

languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "John Doe"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    info = "Full Stack DevOps and Magician"
    avatarurl = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@johndoe"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://myhugosite.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"

    [languages.zh-cn]
        languagename = "Chinese"
        title = "æ„å»ºæˆ‘çš„è¢«åŠ¨æ”¶å…¥"

        [languages.zh-cn.params]
            author = "ssyo"
            info = "self ğŸ¶ dev ğŸ± money"
            description = "é€šè¿‡è‡ªæˆ‘ç®¡ç†ï¼ˆGTDã€æ—¶é—´ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€å†™ä½œã€è´¢åŠ¡ç®¡ç†ï¼‰ã€å…¨æ ˆå¼€å‘ï¼ˆå‰ç«¯ã€åç«¯ã€ç§»åŠ¨ç«¯ã€DevOpsï¼‰ã€æŠ•èµ„äº¤æ˜“ï¼ˆæŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ï¼‰ã€ç½‘èµšé¡¹ç›®ï¼ˆSEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ï¼‰æ¥å»ºç«‹è¢«åŠ¨æ”¶å…¥"
            keywords = "è‡ªæˆ‘ç®¡ç†ã€æ—¶é—´ç®¡ç†ã€GTDã€å†™ä½œã€æ‘„å½±ã€ç¬”è®°ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€è´¢åŠ¡ç®¡ç†ã€å…¨æ ˆå¼€å‘ã€æŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ã€SEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ã€è¢«åŠ¨æ”¶å…¥ã€ç½‘èµš"
            # footercontent = "self/dev/money"

        [languages.zh-cn.menu]

            [[languages.zh-cn.menu.main]]
                name = "å…³äº"
                weight = 1
                url = "/about/"
            [[languages.zh-cn.menu.main]]
                name = "è‡ªæˆ‘ç®¡ç†"
                weight = 2
                url  = "/self/"
            [[languages.zh-cn.menu.main]]
                name = "å…¨æ ˆå¼€å‘"
                weight = 3
                url  = "/dev/"
            [[languages.zh-cn.menu.main]]
                name = "è¢«åŠ¨æ”¶å…¥"
                weight = 4
                url  = "/money/"
            [[languages.zh-cn.menu.main]]
                name = "é¡¹ç›®"
                weight = 5
                url  = "/project/"
            [[languages.zh-cn.menu.main]]
                name = "ç›®æ ‡"
                weight = 6
                url  = "/goal/"
            [[languages.zh-cn.menu.main]]
                name = "æ‰¯æ·¡"
                weight = 7
                url  = "https://tg.bmpi.dev"

googleAnalytics = "UA-123-45"